# Generated by Django 6.0.6 on 2026-07-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_contact_rename_sub_category_product_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("items_json", models.CharField(max_length=5000)),
                ("name", models.CharField(max_length=90)),
                ("email", models.CharField(max_length=111)),
                ("address", models.CharField(max_length=111)),
                ("city", models.CharField(max_length=111)),
                ("state", models.CharField(max_length=111)),
                ("zip_code", models.CharField(max_length=111)),
                ("phone", models.CharField(default="", max_length=111)),
            ],
        ),
    ]
